Acrescenta cota aprovada liquida
splor-mg/dados-totais-armazem-siafi pull request #36
Opened 2024-05-14 21:09 UTC by carloshob

Closes #25 

Acrescenta recurso de cota aprovada líquida, bem como faz atualizações no nosso padrão de nomenclatura. 

**observação:** alguns dos commit's feitos foram prévios ao alinhamento de ignorar arquivos que são gerados automaticamente pelo próprio datapackage. Então, esse PR ainda não poderá ser feito de forma automática. 
Me disponibilizo a fazê-lo quando findadas as validações.

2024-05-16 19:00 UTC, carloshob commented
> @carloshob isso está pronto para revisão?

Está sim Xicão! Eu havia sentido a necessidade de uma conversa prévia, porém após a última atualização, entendi que poderia ser após a revisão, porém acabei não requisitando revisão no git! Feito!

2024-05-17 14:33 UTC, fjuniorr requested changes
Minha primeira ação ao revisar um PR é "rodar" o código que está sendo proposto. Nesse caso eu esperaria ser capaz de executar um `make extract` que falha com

```
make extract
python3 main.py extract
Error: Expected 5 data files but only found 3 in gmail
```

ou um `make transform` que falha com

```
make transform
python3 main.py transform totais_siafi_cota
2024-05-17T11:26:35-0300 INFO  [scripts.transform] Transforming resource totais_siafi_cota
FileNotFoundError: [Errno 2] No such file or directory: 'data-raw/totais_siafi_cota_current.csv'
```

Em alguns casos pode ser que efetivamente não seja possível executar o PR antes de fazermos merge no main e colocarmos em "produção" (eg. algum agendamento de email que não podemos fazer durante o desenvolvimento) mas se esse for o caso precisa de uma explicação do que está acontecendo.

2024-05-17 14:33 UTC, fjuniorr commented on check-data.R
@carloshob não tem a ver com esse PR mas esse arquivo é algo temporário do @hslinhares e pode ser removido

2024-05-21 12:50 UTC, fjuniorr requested changes
@carloshob duas pequenas alterações e pode fazer merge. 

Pra gente conseguir fazer um squash merge, a gente vai primeiro aplicar as alterações do branch `main` no branch `cota-aprov-liquida` e depois fazer um squash merge do `cota-aprov-liquida` no `main`.

2024-05-21 12:50 UTC, fjuniorr commented on checks/rstats/testthat/test_years.R
> +  result <- sort(unique(package$totais_siafi_restos_pagar$ano))
```suggestion
  result <- sort(unique(package$totais_siafi_execucao_cota$ano))
```

2024-05-21 13:27 UTC, merged